### ISSUE TITLE
GitHub Actions Setup

### ISSUE THREAD

**Issue by johnchoi96** [osucoding/WikiAPI#8]
A/C:
- [ ] When PR is created against the main branch or merged, test cases should be executed
- [ ] Enforce code coverage of 50%

Note:
* Use JaCoCo: https://github.com/marketplace/actions/jacoco-report
```
- name: Fail PR if overall coverage is less than 50%
  if: ${{ steps.jacoco.outputs.coverage-overall < 50.0 }}
  uses: actions/github-script@v6
  with:
    script: |
      core.setFailed('Overall coverage is less than 50%!')
```
